spring:
  profiles:
    active: prod

server:
  port: ${PORT:3000}


  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    datasource:
      driverClassName: org.postgresql.Driver
      url: jdbc:postgresql://monorail.proxy.rlwy.net:30689/railway
      username: root
      password: 4de26Fceab6FF654GehHBeaC5H4Ea5f2
    hibernate:
      ddl-auto: update