spring:
  profiles:
    active: dev
    url: ${DATABASE_URL}
    username: ${DATABASE_PASSWORD}
    password: ${DATABASE_PASSWORD}

  jpa:
    generate-ddl: true
    hibernate.ddl-auto: create-drop
  sql:
    init:
      mode: always