spring:
  datasource:
    database-platform: org.hibernate.dialect.MySQLDialect
    datasource:
      driverClassName: org.mysql.Driver
      url: jdbc:mysql://monorail.proxy.rlwy.net:30689/railway
      username: root
      password: 4de26Fceab6FF654GehHBeaC5H4Ea5f2
    hibernate:
      ddl-auto: update

server:
  port: ${PORT:3000}


  sql:
    init:
      mode: always