management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true

info:
  application:
    name: calendario-inteligente
    description: project with spring boot and postgres
    author: No Country s3
    version: '@project.version@'
spring:
  profiles:
    active: dev